-- Migration 019: Add provenance tracking to claims table
-- Mirrors the attribution pattern already used in landscape tables.
-- Enables generated/synthesis claims to be distinguished from extracted ones.

ALTER TABLE claims
    ADD COLUMN IF NOT EXISTS provenance_type TEXT DEFAULT 'extracted';
    -- Values: 'extracted' (from source ingestion), 'generated' (tournament ideas),
    --         'synthesis' (report conclusions)

COMMENT ON COLUMN claims.provenance_type IS
    'Origin of the claim: extracted from source, generated by tournament, or synthesis from report';

-- Index for filtering by provenance in retrieval
CREATE INDEX IF NOT EXISTS idx_claims_provenance ON claims(provenance_type);
