"""Direct Python handler for /ideas jobs.

Idea lifecycle manager — list, rate, develop, and track ideas
generated by /reflect deep.
"""

from __future__ import annotations

import json
import re
import time
from typing import Callable

import structlog

from gateway.models import Event, Job

logger = structlog.get_logger(__name__)


def _load_voice(config) -> str:
    """Load soul.md voice preamble for narrative output."""
    try:
        from pathlib import Path
        from reading_app.memory import MemorySystem
        ms = MemorySystem(Path(config.memory_path))
        return ms.load_voice()
    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def handle_ideas_job(
    event: Event,
    job: Job,
    config,
    executor,
    *,
    on_progress: Callable[[str], None] | None = None,
) -> str:
    """Run /ideas directly."""
    text = event.payload.get("text", "")
    log = logger.bind(job_id=job.id)
    log.info("ideas_handler_start")
    t0 = time.monotonic()

    from reading_app.db import ensure_pool
    ensure_pool()

    subcmd, args = _parse_command(text)
    log = log.bind(subcmd=subcmd)

    if subcmd == "list":
        result = _handle_list(args, log)
    elif subcmd == "rate":
        result = _handle_rate(args, log)
    elif subcmd == "note":
        result = _handle_note(args, log)
    elif subcmd == "develop":
        result = _handle_develop(args, executor, on_progress, log, config=config)
    elif subcmd == "status":
        result = _handle_status_change(args, log)
    elif subcmd == "view":
        result = _handle_view(args, log)
    else:
        result = _handle_list(args, log)  # default to list

    elapsed = time.monotonic() - t0
    log.info("ideas_handler_complete", elapsed_s=round(elapsed, 1))
    return result


# ---------------------------------------------------------------------------
# Command parser
# ---------------------------------------------------------------------------

def _parse_command(text: str) -> tuple[str, str]:
    """Parse '/ideas [subcmd] [args]'.

    Returns (subcmd, remaining_args).
    """
    cleaned = text.strip()
    for prefix in ("/ideas ", "/ideas"):
        if cleaned.lower().startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
            break

    if not cleaned:
        return "list", ""

    parts = cleaned.split(None, 1)
    subcmd = parts[0].lower()
    args = parts[1] if len(parts) > 1 else ""

    known = {"list", "rate", "note", "develop", "status", "view"}
    if subcmd in known:
        return subcmd, args

    # If not a known subcommand, treat as filter for list
    return "list", cleaned


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------

def _handle_list(filter_text: str, log) -> str:
    """List ideas, optionally filtered by status or source."""
    from reading_app.db import get_conn

    with get_conn() as conn:
        if filter_text:
            # Try as status filter
            valid_statuses = {"new", "developing", "tested", "confirmed", "abandoned"}
            if filter_text.lower() in valid_statuses:
                ideas = conn.execute(
                    """SELECT i.*, gc->>'source_id' AS source_id
                       FROM ideas i,
                       LATERAL (SELECT i.generation_context AS gc) sub
                       WHERE i.generation_context->>'status' = %s
                          OR (%s = 'new' AND (i.generation_context->>'status' IS NULL))
                       ORDER BY i.overall_score DESC NULLS LAST
                       LIMIT 30""",
                    (filter_text.lower(), filter_text.lower()),
                ).fetchall()
            else:
                # Search by text
                ideas = conn.execute(
                    """SELECT i.*, i.generation_context->>'source_id' AS source_id
                       FROM ideas i
                       WHERE i.idea_text ILIKE %s
                          OR i.idea_type ILIKE %s
                       ORDER BY i.overall_score DESC NULLS LAST
                       LIMIT 30""",
                    (f"%{filter_text}%", f"%{filter_text}%"),
                ).fetchall()
        else:
            ideas = conn.execute(
                """SELECT i.*, i.generation_context->>'source_id' AS source_id
                   FROM ideas i
                   WHERE i.novelty_check_passed = TRUE
                   ORDER BY i.overall_score DESC NULLS LAST
                   LIMIT 30"""
            ).fetchall()

    if not ideas:
        return (
            "**No ideas found.**\n\n"
            "Generate ideas with `/reflect <source_id> deep`\n"
            "Filter: `/ideas <status>` where status is: new, developing, tested, confirmed, abandoned"
        )

    lines = [f"**Ideas** ({len(ideas)} shown)\n"]

    for i, idea in enumerate(ideas, 1):
        score = idea.get("overall_score") or 0
        idea_type = idea.get("idea_type", "?")
        status = _get_idea_status(idea)
        rating = idea.get("user_rating")
        rating_str = f" {'★' * rating}{'☆' * (5 - rating)}" if rating else ""
        idea_text = (idea.get("idea_text") or "")[:100]

        lines.append(
            f"{i}. **[{idea_type}]** (score: {score:.2f}) {status}{rating_str}\n"
            f"   {idea_text}…\n"
            f"   ID: `{idea['id']}`"
        )

    lines.append(
        "\n---\n"
        "Commands: `/ideas view <id>`, `/ideas rate <id> <1-5>`, "
        "`/ideas note <id> <text>`, `/ideas develop <id>`, "
        "`/ideas status <id> <status>`"
    )

    return "\n".join(lines)


def _handle_view(args: str, log) -> str:
    """View full details of an idea."""
    from reading_app.db import get_conn

    idea_id = args.strip()
    if not idea_id:
        return "Usage: `/ideas view <idea_id>`"

    idea = _get_idea(idea_id)
    if not idea:
        return f"Idea not found: `{idea_id}`"

    lines = [f"**Idea: `{idea_id}`**\n"]

    # Core info
    lines.append(f"**Type:** {idea.get('idea_type', '?')}")
    lines.append(f"**Status:** {_get_idea_status(idea)}")
    lines.append(f"**Score:** {idea.get('overall_score', 0):.2f} "
                 f"(novelty: {idea.get('novelty_score', 0):.2f}, "
                 f"feasibility: {idea.get('feasibility_score', 0):.2f}, "
                 f"impact: {idea.get('impact_score', 0):.2f})")

    rating = idea.get("user_rating")
    if rating:
        lines.append(f"**Your rating:** {'★' * rating}{'☆' * (5 - rating)}")

    lines.append(f"\n**Idea:**\n{idea.get('idea_text', '(no text)')}")

    if idea.get("testability"):
        lines.append(f"\n**Testability:** {idea['testability']}")

    # Grounding
    grounding = idea.get("grounding")
    if grounding:
        if isinstance(grounding, str):
            grounding = json.loads(grounding)
        if isinstance(grounding, list):
            lines.append("\n**Grounding:**")
            for g in grounding[:5]:
                if isinstance(g, dict):
                    lines.append(f"- [{g.get('source_id', '?')}] {g.get('snippet', '')[:120]}")
                else:
                    lines.append(f"- {str(g)[:120]}")

    # User notes
    if idea.get("user_notes"):
        lines.append(f"\n**Your notes:** {idea['user_notes']}")

    # Generation context
    ctx = idea.get("generation_context")
    if ctx:
        if isinstance(ctx, str):
            ctx = json.loads(ctx)
        if isinstance(ctx, dict):
            if ctx.get("source_id"):
                lines.append(f"\n**Source:** `{ctx['source_id']}`")

    # Parent idea
    if idea.get("parent_idea_id"):
        lines.append(f"**Evolved from:** `{idea['parent_idea_id']}`")

    return "\n".join(lines)


def _handle_rate(args: str, log) -> str:
    """Rate an idea 1-5."""
    from reading_app.db import get_conn

    parts = args.strip().split()
    if len(parts) < 2:
        return "Usage: `/ideas rate <idea_id> <1-5>`"

    idea_id = parts[0]
    try:
        rating = int(parts[1])
    except ValueError:
        return "Rating must be an integer 1-5."
    if rating < 1 or rating > 5:
        return "Rating must be between 1 and 5."

    idea = _get_idea(idea_id)
    if not idea:
        return f"Idea not found: `{idea_id}`"

    with get_conn() as conn:
        conn.execute(
            "UPDATE ideas SET user_rating = %s WHERE id = %s",
            (rating, idea_id),
        )
        conn.commit()

    log.info("idea_rated", idea_id=idea_id, rating=rating)
    idea_preview = (idea.get("idea_text") or "")[:80]
    return (
        f"**Rated idea** `{idea_id}` {'★' * rating}{'☆' * (5 - rating)}\n"
        f"_{idea_preview}…_"
    )


def _handle_note(args: str, log) -> str:
    """Add a note to an idea."""
    from reading_app.db import get_conn

    parts = args.strip().split(None, 1)
    if len(parts) < 2:
        return "Usage: `/ideas note <idea_id> <your note text>`"

    idea_id = parts[0]
    note_text = parts[1]

    idea = _get_idea(idea_id)
    if not idea:
        return f"Idea not found: `{idea_id}`"

    # Append to existing notes
    existing = idea.get("user_notes") or ""
    if existing:
        new_notes = existing + "\n\n---\n" + note_text
    else:
        new_notes = note_text

    with get_conn() as conn:
        conn.execute(
            "UPDATE ideas SET user_notes = %s WHERE id = %s",
            (new_notes, idea_id),
        )
        conn.commit()

    log.info("idea_noted", idea_id=idea_id)
    return f"**Note added to idea** `{idea_id}`\n_{note_text[:100]}_"


def _handle_status_change(args: str, log) -> str:
    """Change idea status."""
    from reading_app.db import get_conn

    parts = args.strip().split()
    if len(parts) < 2:
        return (
            "Usage: `/ideas status <idea_id> <new_status>`\n"
            "Statuses: new, developing, tested, confirmed, abandoned"
        )

    idea_id = parts[0]
    new_status = parts[1].lower()

    valid_statuses = {"new", "developing", "tested", "confirmed", "abandoned"}
    if new_status not in valid_statuses:
        return f"Invalid status: `{new_status}`. Must be one of: {', '.join(sorted(valid_statuses))}"

    idea = _get_idea(idea_id)
    if not idea:
        return f"Idea not found: `{idea_id}`"

    # Store status in generation_context
    ctx = idea.get("generation_context") or {}
    if isinstance(ctx, str):
        ctx = json.loads(ctx)
    old_status = ctx.get("status", "new")
    ctx["status"] = new_status

    with get_conn() as conn:
        conn.execute(
            "UPDATE ideas SET generation_context = %s WHERE id = %s",
            (json.dumps(ctx), idea_id),
        )
        conn.commit()

    log.info("idea_status_changed", idea_id=idea_id, old=old_status, new=new_status)
    idea_preview = (idea.get("idea_text") or "")[:80]
    return (
        f"**Idea status updated:** {old_status} → {new_status}\n"
        f"`{idea_id}`\n"
        f"_{idea_preview}…_"
    )


def _handle_develop(args: str, executor, on_progress, log, *, config=None) -> str:
    """Use LLM to develop an idea further — expand, test, ground."""
    from reading_app.db import get_conn
    from retrieval.hybrid import hybrid_retrieve

    idea_id = args.strip()
    if not idea_id:
        return "Usage: `/ideas develop <idea_id>`"

    idea = _get_idea(idea_id)
    if not idea:
        return f"Idea not found: `{idea_id}`"

    if on_progress:
        on_progress(f"Developing idea `{idea_id}`...")

    # Gather evidence
    idea_text = idea.get("idea_text", "")
    evidence_text = "(no evidence found)"
    try:
        results = hybrid_retrieve(idea_text[:300], get_conn, k=8)
        if results:
            evidence_text = "\n".join(
                f"- [{r.get('source_id', '?')}] {(r.get('claim_text') or '')[:150]}"
                for r in results
            )
    except Exception as e:
        log.warning("ideas_develop_search_failed", error=str(e)[:200])

    voice = _load_voice(config) if config else ""
    voice_section = f"\n## Voice & Personality\n{voice}" if voice else ""

    prompt = _DEVELOP_PROMPT.format(
        idea_text=idea_text,
        idea_type=idea.get("idea_type", "?"),
        testability=idea.get("testability", "not specified"),
        grounding=_format_grounding(idea.get("grounding")),
        evidence_text=evidence_text,
        user_notes=idea.get("user_notes") or "(none)",
        voice_section=voice_section,
    )

    try:
        result = executor.run_raw(
            prompt,
            session_id="ideas_develop",
            timeout=120,
        )
        development = result.text
    except Exception as e:
        log.error("ideas_develop_llm_failed", error=str(e)[:200])
        return f"Idea development failed: {str(e)[:200]}"

    # Save development as a note
    existing_notes = idea.get("user_notes") or ""
    development_note = f"[Auto-developed]\n{development}"
    new_notes = (existing_notes + "\n\n---\n" + development_note) if existing_notes else development_note

    with get_conn() as conn:
        # Update notes and set status to developing
        ctx = idea.get("generation_context") or {}
        if isinstance(ctx, str):
            ctx = json.loads(ctx)
        ctx["status"] = "developing"

        conn.execute(
            "UPDATE ideas SET user_notes = %s, generation_context = %s WHERE id = %s",
            (new_notes, json.dumps(ctx), idea_id),
        )
        conn.commit()

    log.info("idea_developed", idea_id=idea_id)

    return (
        f"**Idea Development: `{idea_id}`**\n\n"
        f"{development}\n\n"
        f"---\n"
        f"Status updated to `developing`. Development saved to idea notes."
    )


# ---------------------------------------------------------------------------
# LLM prompt for develop
# ---------------------------------------------------------------------------

_DEVELOP_PROMPT = """\
You are developing an idea from a knowledge engine's tournament pipeline.
Your job is to make this idea more concrete, actionable, and grounded.
{voice_section}
## Idea
{idea_text}

## Metadata
- Type: {idea_type}
- Testability: {testability}
- Grounding: {grounding}

## User Notes
{user_notes}

## Related Library Evidence
{evidence_text}

## Instructions

1. **Expand**: Flesh out the idea into a concrete proposal. What specifically would this look like?
2. **Ground**: Connect it more deeply to the evidence. What specific claims support or challenge it?
3. **Test**: Define 2-3 concrete, actionable tests or experiments that could validate or invalidate this idea.
4. **Risks**: What could go wrong? What assumptions might be wrong?
5. **Next steps**: What would the first concrete step be to pursue this idea?

Be specific and practical. Reference sources and claims by ID where possible.
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _get_idea(idea_id: str) -> dict | None:
    from reading_app.db import get_conn
    with get_conn() as conn:
        return conn.execute(
            "SELECT * FROM ideas WHERE id = %s", (idea_id,)
        ).fetchone()


def _get_idea_status(idea: dict) -> str:
    ctx = idea.get("generation_context") or {}
    if isinstance(ctx, str):
        try:
            ctx = json.loads(ctx)
        except (json.JSONDecodeError, TypeError):
            ctx = {}
    return ctx.get("status", "new")


def _format_grounding(grounding) -> str:
    if not grounding:
        return "(none)"
    if isinstance(grounding, str):
        try:
            grounding = json.loads(grounding)
        except (json.JSONDecodeError, TypeError):
            return grounding[:200]
    if isinstance(grounding, list):
        parts = []
        for g in grounding[:5]:
            if isinstance(g, dict):
                parts.append(f"- [{g.get('source_id', '?')}] {g.get('snippet', '')[:100]}")
            else:
                parts.append(f"- {str(g)[:100]}")
        return "\n".join(parts)
    return str(grounding)[:200]
