"""Seed the 3-level AI taxonomy DAG. Idempotent (ON CONFLICT DO NOTHING).

Auto-generated by scripts/regenerate_taxonomy.py on 2026-03-15 21:12.
"""

from __future__ import annotations

import logging

import psycopg
from psycopg.rows import dict_row

logger = logging.getLogger(__name__)

ALL_NODES = [
    # Level 0 — Meta
    ("meta_foundations", "Foundations", "Core technical building blocks of AI: architecture, training paradigms, and scaling.", 0),
    ("meta_intelligence", "Intelligence & Learning", "Cognitive capabilities, reasoning mechanisms, and learning paradigms driving AI intelligence.", 0),
    ("meta_agency", "Agency & Systems", "Autonomous agent architectures, knowledge infrastructure, and tools enabling AI to act.", 0),
    ("meta_applications", "Applied Domains", "Domain-specific AI deployments across robotics, software, science, and creative media.", 0),
    ("meta_reliability", "Reliability & Understanding", "Safety, alignment, interpretability, and evaluation ensuring AI behaves as intended.", 0),
    ("meta_ecosystem", "AI Ecosystem", "Business models, market dynamics, competitive landscape, and investment context of AI.", 0),

    # Level 1 — Subthemes
    ("pretraining_and_scaling", "Pretraining & Scaling", "How foundation models are trained at scale: data curation, compute scaling laws, and pretraining paradigms.", 1),
    ("model_architecture", "Model Architecture", "Design of neural architectures including attention alternatives, efficiency innovations, and representational structure.", 1),
    ("post_training_methods", "Post-Training Methods", "Techniques applied after pretraining: finetuning, distillation, synthetic data, and test-time adaptation.", 1),
    ("reasoning_and_planning", "Reasoning & Planning", "Chain-of-thought, test-time compute scaling, search algorithms, and mathematical problem-solving.", 1),
    ("reinforcement_learning", "Reinforcement Learning", "RL methods for LLM capability development: RLVR for reasoning, reward modeling, policy optimization, and training dynamics.", 1),
    ("multimodal_models", "Multimodal Models", "Vision-language, unified multimodal, and audio-speech models enabling cross-modal understanding and generation.", 1),
    ("agent_systems", "Agent Systems", "Autonomous agent architectures for software engineering, computer use, multi-agent coordination, and self-improvement.", 1),
    ("knowledge_and_memory", "Knowledge & Memory", "Agent memory architectures, retrieval-augmented generation, and context engineering for knowledge-intensive tasks.", 1),
    ("generative_media", "Generative Media", "Image, video, and world model generation including interactive environments and creative content production.", 1),
    ("robotics_and_embodied_ai", "Robotics & Embodied AI", "Vision-language-action models, robot learning, and spatial intelligence for physical-world AI systems.", 1),
    ("code_and_software_ai", "Code & Software AI", "AI for code generation, software engineering automation, and AI-assisted development workflows.", 1),
    ("scientific_and_medical_ai", "Scientific & Medical AI", "AI for scientific discovery, hypothesis generation, medical diagnosis, and biological modeling.", 1),
    ("alignment_and_safety", "Alignment & Safety", "Methods ensuring AI behaves safely: alignment training, hallucination mitigation, and AI governance.", 1),
    ("interpretability", "Interpretability", "Mechanistic analysis of model internals, behavioral characterization, and understanding of AI computation.", 1),
    ("evaluation_and_benchmarks", "Evaluation & Benchmarks", "Benchmark design, evaluation methodology, saturation detection, and agent capability assessment.", 1),
    ("ai_market_dynamics", "AI Market Dynamics", "Competitive landscape, model commoditization, open-source dynamics, and hardware infrastructure economics.", 1),
    ("ai_business_and_economics", "AI Business & Economics", "Vertical AI products, SaaS disruption, AI pricing models, and the economics of deploying AI at scale.", 1),
    ("startup_and_investment", "Startup & Investment", "VC funding dynamics, startup formation strategies, competitive moats, and investment frameworks for AI.", 1),

    # Level 2 — Subsubthemes
    ("scaling_laws", "Scaling Laws", "Empirical and theoretical relationships between training compute, data, parameters, and capability including inference-time scaling axes.", 2),
    ("pretraining_data", "Pretraining Data", "Data curation pipelines, quality filtering, synthetic pretraining corpora, and data scaling strategies for foundation models.", 2),
    ("continual_learning", "Continual Learning", "Lifelong learning methods, catastrophic forgetting prevention, and approaches for ongoing model adaptation without degradation.", 2),
    ("transformer_alternatives", "Transformer Alternatives", "SSMs, Mamba, hybrid architectures, and non-transformer sequence models offering alternatives to standard attention.", 2),
    ("long_context_and_attention", "Long-Context & Attention", "Attention mechanisms and memory-augmented architectures enabling efficient very long context processing.", 2),
    ("adaptive_computation", "Adaptive Computation", "Mixture-of-experts, conditional compute, and architectures that allocate compute dynamically based on input difficulty.", 2),
    ("representation_learning", "Representation Learning", "Embedding architectures, JEPA-style joint-embedding predictive models, and theories of universal representational convergence.", 2),
    ("finetuning_and_distillation", "Finetuning & Distillation", "Supervised finetuning, knowledge distillation, preference learning, and post-training pipelines for capability transfer.", 2),
    ("synthetic_data_generation", "Synthetic Data Generation", "Automated generation of high-quality training data using models for both pretraining and post-training stages.", 2),
    ("in_context_and_meta_learning", "In-Context & Meta-Learning", "Mechanics of in-context learning, meta-learning for rapid adaptation, and self-adaptive language model approaches.", 2),
    ("test_time_learning", "Test-Time Learning", "Inference-time adaptation including TTT, TTRL, and approaches that update model parameters or context on individual inputs.", 2),
    ("chain_of_thought", "Chain-of-Thought Mechanics", "CoT reasoning mechanics, trace quality, reasoning length effects, and efficient reasoning process generation.", 2),
    ("test_time_compute_scaling", "Test-Time Compute Scaling", "Scaling inference compute through extended reasoning, repeated sampling, budget forcing, and compute-optimal search.", 2),
    ("latent_reasoning", "Latent & Continuous Reasoning", "Reasoning in continuous latent space including Coconut, looped transformers, and recurrent depth approaches.", 2),
    ("search_and_tree_reasoning", "Search & Tree-Based Reasoning", "MCTS, tree-of-thought, language agent tree search, and deliberate planning via structured search over reasoning paths.", 2),
    ("mathematical_and_formal_reasoning", "Mathematical & Formal Reasoning", "Theorem proving, olympiad-level mathematics, formal verification, and symbolic reasoning with language models.", 2),
    ("rl_for_llm_reasoning", "RL for LLM Reasoning (RLVR)", "RL with verifiable rewards eliciting reasoning including DeepSeek-R1, Kimi k1.5, self-play, and expert iteration.", 2),
    ("reward_modeling", "Reward Modeling & Verification", "Process and outcome reward models, generative reward models, critique models, and automated verification systems.", 2),
    ("policy_optimization", "Policy Optimization Algorithms", "PPO, GRPO, DPO, FlowRL, and algorithmic innovations for stable and efficient LLM policy optimization.", 2),
    ("rl_theory_and_dynamics", "RL Theory & Training Dynamics", "Theoretical analysis of RL for LLMs covering exploration, entropy dynamics, reward limits, and training stability.", 2),
    ("vision_language_models", "Vision-Language Models", "Perception-focused VLMs for visual understanding, document analysis, multimodal QA, and visual chain-of-thought reasoning.", 2),
    ("unified_multimodal_models", "Unified Multimodal Models", "Single architectures integrating both multimodal understanding and generation across images, text, and other modalities.", 2),
    ("audio_and_speech_models", "Audio & Speech Models", "Real-time voice dialogue, speech synthesis, audio-language models, and multimodal audio-visual understanding.", 2),
    ("software_engineering_agents", "Software Engineering Agents", "AI agents for code generation, debugging, repository-level tasks, and end-to-end software engineering automation.", 2),
    ("computer_use_and_gui_agents", "Computer Use & GUI Agents", "Agents operating web browsers, desktop GUIs, and arbitrary computer interfaces through visual grounding and action.", 2),
    ("multi_agent_coordination", "Multi-Agent Coordination", "Architectures for coordinating multiple AI agents including hierarchical orchestration, peer-to-peer, and role specialization.", 2),
    ("tool_use_and_agent_protocols", "Tool Use & Agent Protocols", "Function calling, tool-integrated reasoning, MCP, A2A protocol, and infrastructure for agent-world interaction.", 2),
    ("agent_self_evolution", "Agent Self-Evolution", "Self-improving agents, open-ended skill acquisition, and systems that autonomously expand their own capabilities.", 2),
    ("agent_memory_systems", "Agent Memory Systems", "Long-term and short-term memory architectures enabling AI agents to retain and retrieve accumulated experience.", 2),
    ("retrieval_augmented_generation", "Retrieval-Augmented Generation", "RAG architectures, graph-based knowledge retrieval, and knowledge-augmented generation for grounded AI responses.", 2),
    ("context_engineering", "Context Engineering", "Deliberate shaping of agent context windows, KV-cache optimization, and stateful context management for production agents.", 2),
    ("image_generation_models", "Image Generation Models", "Autoregressive and diffusion image generation, visual tokenization architectures, and high-resolution synthesis approaches.", 2),
    ("video_and_world_models", "Video & World Models", "Video generation, interactive world simulators, physics-grounded world foundation models, and game-engine synthesis.", 2),
    ("creative_content_generation", "Creative Content Generation", "AI for human animation, film production, music, and professional-quality creative media generation.", 2),
    ("vision_language_action_models", "Vision-Language-Action Models", "VLA models connecting visual perception and language understanding to robot action for generalist control.", 2),
    ("robot_learning", "Robot Learning", "Imitation learning, sim-to-real transfer, dexterous manipulation, locomotion, and policy learning for physical robots.", 2),
    ("spatial_and_3d_intelligence", "Spatial & 3D Intelligence", "Spatial reasoning, 3D scene understanding, world-grounded navigation, and geometric intelligence for embodied AI.", 2),
    ("code_generation", "Code Generation", "LLM-based code synthesis, program generation from natural language, and automated code completion systems.", 2),
    ("ai_software_engineering", "AI Software Engineering", "AI-driven full software development lifecycle including testing, refactoring, code review, and CI/CD automation.", 2),
    ("ai_for_scientific_discovery", "AI for Scientific Discovery", "Autonomous hypothesis generation, open mathematical problem solving, and AI-driven end-to-end research workflows.", 2),
    ("medical_and_biology_ai", "Medical & Biology AI", "AI for medical diagnosis, drug discovery, single-cell biology, protein modeling, and clinical decision support.", 2),
    ("alignment_methods", "Alignment Methods", "RLHF, constitutional AI, deliberative alignment, and techniques for producing reliably safe and beneficial AI behavior.", 2),
    ("ai_governance", "AI Governance & Policy", "Regulatory frameworks, existential risk governance, power dynamics, and societal impact of advanced AI systems.", 2),
    ("hallucination_and_reliability", "Hallucination & Reliability", "Factual calibration, uncertainty quantification, hallucination detection, and reliability mitigation for deployed models.", 2),
    ("mechanistic_interpretability", "Mechanistic Interpretability", "Circuit-level analysis, feature attribution, thought tracing, and mechanistic understanding of AI model computation.", 2),
    ("model_behavior_analysis", "Model Behavior Analysis", "Behavioral characterization, capability elicitation, jagged intelligence patterns, and persona analysis in deployed models.", 2),
    ("benchmark_design", "Benchmark Design & Saturation", "Creating robust evaluation benchmarks, addressing data contamination, saturation dynamics, and evaluation best practices.", 2),
    ("agent_evaluation", "Agent & Task Evaluation", "Evaluation frameworks for agentic systems, tool use benchmarks, reasoning evals, and long-horizon task assessment.", 2),
    ("model_commoditization_and_open_source", "Commoditization & Open Source", "Open-source model dynamics, commoditization of frontier capabilities, and competitive implications of releases like DeepSeek.", 2),
    ("compute_and_hardware", "Compute & Hardware", "GPU market dynamics, semiconductor landscape, data center infrastructure investment, and compute economics.", 2),
    ("frontier_lab_competition", "Frontier Lab Competition", "Competitive dynamics between leading AI labs, market share shifts, model release timing, and strategic positioning.", 2),
    ("vertical_ai_and_saas_disruption", "Vertical AI & SaaS Disruption", "Domain-specific AI companies, disruption of incumbent SaaS vendors, and the AI-native product architecture shift.", 2),
    ("ai_pricing_and_business_models", "AI Pricing & Business Models", "Outcome-based pricing, token economics, unit economics of AI services, and business model innovation in the AI era.", 2),
    ("vc_and_startup_ecosystem", "VC & Startup Ecosystem", "Venture capital investment patterns, startup formation dynamics, funding rounds, and investor frameworks for AI companies.", 2),
    ("startup_formation_and_gtm", "Startup Formation & Go-to-Market", "Competitive moat building, go-to-market sequencing, market timing, and early-stage strategy for AI startups.", 2),

]

HIERARCHY_EDGES = [
    ("meta_foundations", "pretraining_and_scaling", "contains", 1.0),
    ("meta_foundations", "model_architecture", "contains", 1.0),
    ("meta_foundations", "post_training_methods", "contains", 1.0),
    ("meta_intelligence", "reasoning_and_planning", "contains", 1.0),
    ("meta_intelligence", "reinforcement_learning", "contains", 1.0),
    ("meta_intelligence", "multimodal_models", "contains", 1.0),
    ("meta_agency", "agent_systems", "contains", 1.0),
    ("meta_agency", "knowledge_and_memory", "contains", 1.0),
    ("meta_applications", "generative_media", "contains", 1.0),
    ("meta_applications", "robotics_and_embodied_ai", "contains", 1.0),
    ("meta_applications", "code_and_software_ai", "contains", 1.0),
    ("meta_applications", "scientific_and_medical_ai", "contains", 1.0),
    ("meta_reliability", "alignment_and_safety", "contains", 1.0),
    ("meta_reliability", "interpretability", "contains", 1.0),
    ("meta_reliability", "evaluation_and_benchmarks", "contains", 1.0),
    ("meta_ecosystem", "ai_market_dynamics", "contains", 1.0),
    ("meta_ecosystem", "ai_business_and_economics", "contains", 1.0),
    ("meta_ecosystem", "startup_and_investment", "contains", 1.0),
    ("pretraining_and_scaling", "scaling_laws", "contains", 1.0),
    ("pretraining_and_scaling", "pretraining_data", "contains", 1.0),
    ("pretraining_and_scaling", "continual_learning", "contains", 1.0),
    ("model_architecture", "transformer_alternatives", "contains", 1.0),
    ("model_architecture", "long_context_and_attention", "contains", 1.0),
    ("model_architecture", "adaptive_computation", "contains", 1.0),
    ("model_architecture", "representation_learning", "contains", 1.0),
    ("post_training_methods", "finetuning_and_distillation", "contains", 1.0),
    ("post_training_methods", "synthetic_data_generation", "contains", 1.0),
    ("post_training_methods", "in_context_and_meta_learning", "contains", 1.0),
    ("post_training_methods", "test_time_learning", "contains", 1.0),
    ("reasoning_and_planning", "chain_of_thought", "contains", 1.0),
    ("reasoning_and_planning", "test_time_compute_scaling", "contains", 1.0),
    ("reasoning_and_planning", "latent_reasoning", "contains", 1.0),
    ("reasoning_and_planning", "search_and_tree_reasoning", "contains", 1.0),
    ("reasoning_and_planning", "mathematical_and_formal_reasoning", "contains", 1.0),
    ("reinforcement_learning", "rl_for_llm_reasoning", "contains", 1.0),
    ("reinforcement_learning", "reward_modeling", "contains", 1.0),
    ("reinforcement_learning", "policy_optimization", "contains", 1.0),
    ("reinforcement_learning", "rl_theory_and_dynamics", "contains", 1.0),
    ("multimodal_models", "vision_language_models", "contains", 1.0),
    ("multimodal_models", "unified_multimodal_models", "contains", 1.0),
    ("multimodal_models", "audio_and_speech_models", "contains", 1.0),
    ("agent_systems", "software_engineering_agents", "contains", 1.0),
    ("agent_systems", "computer_use_and_gui_agents", "contains", 1.0),
    ("agent_systems", "multi_agent_coordination", "contains", 1.0),
    ("agent_systems", "tool_use_and_agent_protocols", "contains", 1.0),
    ("agent_systems", "agent_self_evolution", "contains", 1.0),
    ("knowledge_and_memory", "agent_memory_systems", "contains", 1.0),
    ("knowledge_and_memory", "retrieval_augmented_generation", "contains", 1.0),
    ("knowledge_and_memory", "context_engineering", "contains", 1.0),
    ("generative_media", "image_generation_models", "contains", 1.0),
    ("generative_media", "video_and_world_models", "contains", 1.0),
    ("generative_media", "creative_content_generation", "contains", 1.0),
    ("robotics_and_embodied_ai", "vision_language_action_models", "contains", 1.0),
    ("robotics_and_embodied_ai", "robot_learning", "contains", 1.0),
    ("robotics_and_embodied_ai", "spatial_and_3d_intelligence", "contains", 1.0),
    ("code_and_software_ai", "code_generation", "contains", 1.0),
    ("code_and_software_ai", "ai_software_engineering", "contains", 1.0),
    ("scientific_and_medical_ai", "ai_for_scientific_discovery", "contains", 1.0),
    ("scientific_and_medical_ai", "medical_and_biology_ai", "contains", 1.0),
    ("alignment_and_safety", "alignment_methods", "contains", 1.0),
    ("alignment_and_safety", "ai_governance", "contains", 1.0),
    ("alignment_and_safety", "hallucination_and_reliability", "contains", 1.0),
    ("interpretability", "mechanistic_interpretability", "contains", 1.0),
    ("interpretability", "model_behavior_analysis", "contains", 1.0),
    ("evaluation_and_benchmarks", "benchmark_design", "contains", 1.0),
    ("evaluation_and_benchmarks", "agent_evaluation", "contains", 1.0),
    ("ai_market_dynamics", "model_commoditization_and_open_source", "contains", 1.0),
    ("ai_market_dynamics", "compute_and_hardware", "contains", 1.0),
    ("ai_market_dynamics", "frontier_lab_competition", "contains", 1.0),
    ("ai_business_and_economics", "vertical_ai_and_saas_disruption", "contains", 1.0),
    ("ai_business_and_economics", "ai_pricing_and_business_models", "contains", 1.0),
    ("startup_and_investment", "vc_and_startup_ecosystem", "contains", 1.0),
    ("startup_and_investment", "startup_formation_and_gtm", "contains", 1.0),
]

CROSS_CUTTING_EDGES = [
    ("reinforcement_learning", "reasoning_and_planning", "enables", 0.95),
    ("reasoning_and_planning", "agent_systems", "enables", 0.9),
    ("knowledge_and_memory", "agent_systems", "enables", 0.88),
    ("multimodal_models", "robotics_and_embodied_ai", "enables", 0.9),
    ("model_architecture", "reasoning_and_planning", "enables", 0.8),
    ("model_architecture", "multimodal_models", "enables", 0.82),
    ("pretraining_and_scaling", "reinforcement_learning", "related", 0.8),
    ("reinforcement_learning", "alignment_and_safety", "related", 0.82),
    ("interpretability", "alignment_and_safety", "enables", 0.85),
    ("evaluation_and_benchmarks", "reasoning_and_planning", "constrains", 0.75),
    ("agent_systems", "ai_business_and_economics", "enables", 0.88),
    ("agent_systems", "code_and_software_ai", "related", 0.82),
    ("generative_media", "robotics_and_embodied_ai", "enables", 0.78),
    ("ai_market_dynamics", "ai_business_and_economics", "related", 0.85),
    ("post_training_methods", "reinforcement_learning", "related", 0.78),
    ("reasoning_and_planning", "scientific_and_medical_ai", "enables", 0.8),
    ("multimodal_models", "generative_media", "related", 0.72),
    ("ai_market_dynamics", "pretraining_and_scaling", "constrains", 0.72),
]


def seed_themes(dsn: str):
    """Insert all themes and edges. Idempotent."""
    with psycopg.connect(dsn, row_factory=dict_row) as conn:
        for theme_id, name, description, level in ALL_NODES:
            conn.execute(
                """INSERT INTO themes (id, name, description, level)
                   VALUES (%s, %s, %s, %s) ON CONFLICT (id) DO NOTHING""",
                (theme_id, name, description, level),
            )

        all_edges = HIERARCHY_EDGES + CROSS_CUTTING_EDGES
        for parent_id, child_id, relationship, strength in all_edges:
            conn.execute(
                """INSERT INTO theme_edges (parent_id, child_id, relationship, strength)
                   VALUES (%s, %s, %s, %s) ON CONFLICT (parent_id, child_id) DO NOTHING""",
                (parent_id, child_id, relationship, strength),
            )

        conn.commit()

    meta = [n for n in ALL_NODES if n[3] == 0]
    subthemes = [n for n in ALL_NODES if n[3] == 1]
    subsubthemes = [n for n in ALL_NODES if n[3] == 2]
    logger.info(
        "Seeded %d meta + %d subthemes + %d subsubthemes (%d total), %d edges",
        len(meta), len(subthemes), len(subsubthemes), len(ALL_NODES), len(all_edges),
    )


def main():
    logging.basicConfig(level=logging.INFO)
    from reading_app.config import Config
    config = Config()
    seed_themes(config.postgres_dsn)


if __name__ == "__main__":
    main()
